Updated with minor changes.
VB10/flutter-ready-to-use-widgets pull request #31
Opened 2022-09-06 08:43 UTC by mustafauys

- Color constants file added.
- The page structure has been edited.
- Construction update.
- Pubspec lock version update.
- The colors have been updated to pull from the constant folder.

2022-09-16 20:25 UTC, VB10 requested changes
eline sağlık gif veya resim ekler misin

2022-09-19 10:45 UTC, mustafauys commented
- Readme düzenlendi, resim eklendi.
- Tema alt yapısı oluşturuldu.
- Google fonts paketi pubspec eklendi.
- Color constants klasörüne açıklama eklendi.

2022-09-23 13:46 UTC, VB10 requested changes
bir iki ekleme

2022-09-23 13:46 UTC, VB10 commented on lib/atomic/button/asynchronous_button.dart
>  final buttonStyle = ButtonStyle(
bunu bir classa alalim styler oradan gelsin color propertlyerde constlardan gelsin

2022-09-23 13:46 UTC, VB10 commented on lib/atomic/glow_image/example_glow_image.dart
> +    const _width = 300.0;
width burad atutamylaim ustte veriabvle

2022-09-24 20:21 UTC, VB10 commented
@mustafauys ben bu seilde aliyorum sonra duzeltirsin sen

2022-09-24 20:21 UTC, merged

2022-09-24 22:44 UTC, mustafauys commented
@VB10 en kısa zamanda güncelleme atacağım.